name: Format 
on:
  push:
    branches: [main]
    paths:
      - '**.lua'
      - '.stylua.toml'
      - '.github/workflows/lint.yml'
  pull_request:

jobs:
  stylua:
    name: Check Lua formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lua/ --config-path=.stylua.toml
