name: Lint
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install luarocks -y
          sudo luarocks install luacheck

      - name: Lint
        run: luacheck lua/ --globals vim
