name: Tests
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependencies 
        run: |
          mkdir dependencies
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git dependencies/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git dependencies/nvim-treesitter
      
      - name: Prepare
        run: |
          npm install tree-sitter-cli

      - name: Run tests
        run: |
          ls -la dependencies
          echo "Run tests using make"
