name: Tests
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ --config-path=.stylua.toml

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependencies 
        run: |
          mkdir -p dependencies
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git dependencies/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git dependencies/nvim-treesitter
      
      - name: Prepare
        run: |
          mkdir -p _nvim
          curl -sL "https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_nvim"
          export PATH="${PWD}/_nvim/bin:${PATH}"
          
          nvim --headless -u scripts/minimal.vim -c 'TSUpdateSync javascript' -c 'q'
      
      - name: Run tests
        run: |
          export PATH="${PWD}/_nvim/bin:${PATH}"
          nvim --version
          make test
